// Embedded Fallback Data for GitHub Pages & Static Demonstration
export const MOCK_JOBS = [
  {
    id: 1,
    title: "Senior AI / Machine Learning Engineer",
    department: "Artificial Intelligence & Cognitive Systems",
    location: "Bangalore, India (Hybrid)",
    employment_type: "Full-time",
    experience_level: "Senior",
    openings: 3,
    status: "ACTIVE",
    min_score_threshold: 70.0,
    category_thresholds: { "Technical Skills": 65.0, "Problem Solving": 60.0 },
    created_at: "2026-09-13T10:00:00",
    requirements_count: 14,
    applications_count: 4,
    description: "Architect and scale distributed deep learning microservices, transformer inference pipelines, and autonomous agentic workflows."
  },
  {
    id: 2,
    title: "Full Stack & Distributed Systems Engineer",
    department: "Engineering Architecture",
    location: "Hyderabad, India (Hybrid)",
    employment_type: "Full-time",
    experience_level: "Mid-Senior",
    openings: 2,
    status: "ACTIVE",
    min_score_threshold: 70.0,
    category_thresholds: { "Technical Skills": 65.0, "Problem Solving": 60.0 },
    created_at: "2026-09-13T10:05:00",
    requirements_count: 12,
    applications_count: 3,
    description: "Design high-throughput event-driven microservices, distributed caching layers, and resilient customer-facing workflows."
  },
  {
    id: 3,
    title: "Cloud Infrastructure & DevOps Architect",
    department: "Cloud & Infrastructure Operations",
    location: "Remote",
    employment_type: "Full-time",
    experience_level: "Lead",
    openings: 2,
    status: "ACTIVE",
    min_score_threshold: 65.0,
    category_thresholds: { "Technical Skills": 60.0, "Problem Solving": 60.0 },
    created_at: "2026-09-13T10:10:00",
    requirements_count: 10,
    applications_count: 2,
    description: "Manage multi-region Kubernetes clusters, automated GitOps deployment pipelines, and high-availability cloud infrastructure."
  },
  {
    id: 4,
    title: "Frontend Architecture & UI/UX Specialist",
    department: "Product Experience",
    location: "Remote",
    employment_type: "Full-time",
    experience_level: "Mid-Senior",
    openings: 2,
    status: "ACTIVE",
    min_score_threshold: 65.0,
    category_thresholds: { "Technical Skills": 60.0, "Problem Solving": 55.0 },
    created_at: "2026-09-13T10:15:00",
    requirements_count: 11,
    applications_count: 2,
    description: "Lead modern React design systems, micro-interactions, responsive accessibility, and canvas visual components."
  },
  {
    id: 5,
    title: "Data Analytics & Strategic Intelligence Engineer",
    department: "Business Intelligence",
    location: "Mumbai, India (Hybrid)",
    employment_type: "Full-time",
    experience_level: "Mid-Level",
    openings: 2,
    status: "ACTIVE",
    min_score_threshold: 65.0,
    category_thresholds: { "Technical Skills": 60.0, "Problem Solving": 60.0 },
    created_at: "2026-09-13T10:20:00",
    requirements_count: 9,
    applications_count: 2,
    description: "Build predictive data models, streaming analytics pipelines, and executive intelligence dashboards."
  },
  {
    id: 9,
    title: "Principal Cognitive Systems Engineer",
    department: "Artificial Intelligence & Data Science",
    location: "Bangalore, India",
    employment_type: "Full-time",
    experience_level: "Lead",
    openings: 1,
    status: "ACTIVE",
    min_score_threshold: 75.0,
    category_thresholds: { "Technical Skills": 70.0, "Problem Solving": 70.0 },
    created_at: "2026-09-13T11:00:00",
    requirements_count: 15,
    applications_count: 4,
    description: "Direct enterprise neural orchestration systems, multi-agent frameworks, and continuous evaluation benchmarks."
  }
];

export const MOCK_APPLICATIONS = [
  {
    id: 13,
    job_id: 9,
    job_title: "Principal Cognitive Systems Engineer",
    job_department: "Artificial Intelligence & Cognitive Systems",
    status: "Offer Extended",
    overall_match_score: 94.2,
    applied_at: "2026-09-13T11:05:00",
    candidate_name: "Sayan Rooj",
    candidate_email: "sayanrooj742137@gmail.com",
    stage: "Stage 3: Extend Domain Offer",
    interview_score: 92.5,
    interview_status: "COMPLETED",
    recommendation: "Strong Hire",
    feedback: "Demonstrated exceptional mastery across neural architectures and distributed event systems."
  },
  {
    id: 1,
    job_id: 1,
    job_title: "Senior AI / Machine Learning Engineer",
    job_department: "Artificial Intelligence & Cognitive Systems",
    status: "Face-to-Face Scheduled",
    overall_match_score: 92.4,
    applied_at: "2026-09-13T10:30:00",
    candidate_name: "Aarav Sharma",
    candidate_email: "aarav.sharma@example.com",
    stage: "Stage 2: Face-to-Face Round",
    interview_score: 88.0,
    interview_status: "COMPLETED",
    recommendation: "Hire",
    feedback: "Strong grasp of transformer fine-tuning and PyTorch deployment."
  },
  {
    id: 2,
    job_id: 2,
    job_title: "Full Stack & Distributed Systems Engineer",
    job_department: "Engineering Architecture",
    status: "Shortlisted",
    overall_match_score: 88.5,
    applied_at: "2026-09-13T10:35:00",
    candidate_name: "Priya Patel",
    candidate_email: "priya.patel@example.com",
    stage: "Stage 1: AI Assessment",
    interview_score: 85.0,
    interview_status: "SCHEDULED",
    recommendation: "Proceed",
    feedback: "High proficiency in distributed microservices and reactive interfaces."
  }
];
